import MediaInfo from '../core/media-info';
import { PESPrivateData, PESPrivateDataDescriptor } from './pes-private-data';
import { SMPTE2038Data } from './smpte2038';
import { SCTE35Data } from './scte35';
import { KLVData } from './klv';
import { PGSData } from './pgs-data';
import { SEIData } from './sei';
type OnErrorCallback = (type: string, info: string) => void;
type OnMediaInfoCallback = (mediaInfo: MediaInfo) => void;
type OnMetaDataArrivedCallback = (metadata: any) => void;
type OnTrackMetadataCallback = (type: string, metadata: any) => void;
type OnDataAvailableCallback = (audioTrack: any, videoTrack: any, force?: boolean) => void;
type OnTimedID3MetadataCallback = (timed_id3_data: PESPrivateData) => void;
type onPGSSubitleDataCallback = (pgs_data: PGSData) => void;
type OnSynchronousKLVMetadataCallback = (synchronous_klv_data: KLVData) => void;
type OnAsynchronousKLVMetadataCallback = (asynchronous_klv_data: PESPrivateData) => void;
type OnSMPTE2038MetadataCallback = (smpte2038_data: SMPTE2038Data) => void;
type OnSEICallback = (sei_data: SEIData) => void;
type OnSCTE35MetadataCallback = (scte35_data: SCTE35Data) => void;
type OnPESPrivateDataCallback = (private_data: PESPrivateData) => void;
type OnPESPrivateDataDescriptorCallback = (private_data_descriptor: PESPrivateDataDescriptor) => void;
export default abstract class BaseDemuxer {
    onError: OnErrorCallback | null;
    onMediaInfo: OnMediaInfoCallback | null;
    onMetaDataArrived: OnMetaDataArrivedCallback | null;
    onTrackMetadata: OnTrackMetadataCallback | null;
    onDataAvailable: OnDataAvailableCallback | null;
    onTimedID3Metadata: OnTimedID3MetadataCallback | null;
    onPGSSubtitleData: onPGSSubitleDataCallback | null;
    onSynchronousKLVMetadata: OnSynchronousKLVMetadataCallback | null;
    onAsynchronousKLVMetadata: OnAsynchronousKLVMetadataCallback | null;
    onSMPTE2038Metadata: OnSMPTE2038MetadataCallback | null;
    onSEI: OnSEICallback | null;
    onSCTE35Metadata: OnSCTE35MetadataCallback | null;
    onPESPrivateData: OnPESPrivateDataCallback | null;
    onPESPrivateDataDescriptor: OnPESPrivateDataDescriptorCallback | null;
    constructor();
    destroy(): void;
    abstract parseChunks(chunk: ArrayBuffer, byteStart: number): number;
}
export {};
