export function createDefaultConfig(): {
    enableWorker: boolean;
    enableWorkerForMSE: boolean;
    enableStashBuffer: boolean;
    stashInitialSize: undefined;
    isLive: boolean;
    liveBufferLatencyChasing: boolean;
    liveBufferLatencyChasingOnPaused: boolean;
    liveBufferLatencyMaxLatency: number;
    liveBufferLatencyMinRemain: number;
    liveSync: boolean;
    liveSyncMaxLatency: number;
    liveSyncTargetLatency: number;
    liveSyncPlaybackRate: number;
    lazyLoad: boolean;
    lazyLoadMaxDuration: number;
    lazyLoadRecoverDuration: number;
    deferLoadAfterSourceOpen: boolean;
    autoCleanupMaxBackwardDuration: number;
    autoCleanupMinBackwardDuration: number;
    statisticsInfoReportInterval: number;
    fixAudioTimestampGap: boolean;
    accurateSeek: boolean;
    seekType: string;
    seekParamStart: string;
    seekParamEnd: string;
    rangeLoadZeroStart: boolean;
    customSeekHandler: undefined;
    reuseRedirectedURL: boolean;
    headers: undefined;
    customLoader: undefined;
};
export namespace defaultConfig {
    let enableWorker: boolean;
    let enableWorkerForMSE: boolean;
    let enableStashBuffer: boolean;
    let stashInitialSize: undefined;
    let isLive: boolean;
    let liveBufferLatencyChasing: boolean;
    let liveBufferLatencyChasingOnPaused: boolean;
    let liveBufferLatencyMaxLatency: number;
    let liveBufferLatencyMinRemain: number;
    let liveSync: boolean;
    let liveSyncMaxLatency: number;
    let liveSyncTargetLatency: number;
    let liveSyncPlaybackRate: number;
    let lazyLoad: boolean;
    let lazyLoadMaxDuration: number;
    let lazyLoadRecoverDuration: number;
    let deferLoadAfterSourceOpen: boolean;
    let autoCleanupMaxBackwardDuration: number;
    let autoCleanupMinBackwardDuration: number;
    let statisticsInfoReportInterval: number;
    let fixAudioTimestampGap: boolean;
    let accurateSeek: boolean;
    let seekType: string;
    let seekParamStart: string;
    let seekParamEnd: string;
    let rangeLoadZeroStart: boolean;
    let customSeekHandler: undefined;
    let reuseRedirectedURL: boolean;
    let headers: undefined;
    let customLoader: undefined;
}
